CREATE TABLE `T_Stations` (
  `IDNO` bigint NOT NULL AUTO_INCREMENT,
  `StationName` varchar(100) NOT NULL,
  `Last_Active` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `INSERT_TS` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATE_TS` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`IDNO`),
  UNIQUE KEY `IDNO_UNIQUE` (`IDNO`),
  UNIQUE KEY `StationName_UNIQUE` (`StationName`)
) ENGINE=InnoDB AUTO_INCREMENT=13 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
